# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'git@github.com:1070824493/Specs.git'
source 'https://cdn.cocoapods.org/'
use_frameworks!

workspace 'MainProject.xcworkspace'

# MARK: -- Target: MainProject
target 'MainProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end

def pods_ModuleFoundation
#  pod 'MikCore'
  pod 'MikCore', :git => 'https://github.com/1070824493/MikCore.git', :branch => 'master'
end
def pods_ModuleLogin

end
def pods_ModuleResource

end

target 'ModuleFoundation' do

  project 'ModuleFoundation/ModuleFoundation.xcodeproj'
  pods_ModuleFoundation
end

target 'ModuleLogin' do
  project 'ModuleLogin/ModuleLogin.xcodeproj'
end

target 'ModuleResource' do
  project 'ModuleResource/ModuleResource.xcodeproj'
end




